### ISSUE TITLE
Print Build or Version Information On Splash Screen On Bottom Right

### ISSUE THREAD

**Issue by Sn3akyP3t3** [wpilibsuite/FRCVision-pi-gen#95] opened 2019-02-06 04:13 UTC
Just a suggestion for quick confirmation capabilities to the user to be able to view what version of the build they are using.

What alternative method is there to confirm what build or version of the image they are running?

**Comment by PeterJohnson** [comment] 2019-02-06 04:14
Yes, good idea.  Duplicate of #94 (just opened this).

**Comment by Sn3akyP3t3** [comment] 2019-02-06 04:21
Meanwhile what method do people have to confirm what build they are currently running?

I tried a handful of things and this brings me close, but not sure if it is best:
pi@spacialturboencabulator(rw):~$ cat /etc/rpi-issue
Raspberry Pi reference 2019-01-14
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 08163c06810aa506fea56d101e2a1e4d683e0b02, stage2

If that is the build date I'm probably rocking the older kickoff date version, but that may have been me following an old link.

**Comment by PeterJohnson** [comment] 2019-02-06 05:40
That's the build date, so you're running 2019.2.1

**Closed** 2019-02-18 09:22 UTC
Labels: enhancement, webdash
